#!/bin/bash
set -euo pipefail

mkdir -p $HOME/Desktop

# Copy desktop files over on container start rather than on postBuild
# In JupyterHubs, $HOME in build time is not available during runtime
# as $HOME is usually a persistent directory mounted per user
cp $REPO_DIR/*.desktop $HOME/Desktop/

# Tell code running in notebooks and jupyter terminals where DISPLAY is, 
# so they know where to launch GUI 
export DISPLAY=:1.0

exec "$@"
